application: election-maps
version: sc2012
runtime: python
api_version: 1

default_expiration: "2m"

handlers:

- url: /(vote-data|.*\.html)
  script: results-app.py
  
- url: /(css/.*|images/.*|js/.*|shapes/.*)
  static_files: static/\1
  upload: static/(css/.*|images/.*|js/.*|shapes/.*)
